### ISSUE TITLE
Use more appropriate data types for representing file names and possibly passwords

### ISSUE THREAD

**Issue by Kixunil** [muja/unrar.rs#4] opened 2017-05-07 13:10 UTC
First of all, `String` allows only UTF8, which means that it's impossible to open non-UTF8 named archives. Secondly, I'm not sure how (and whether) it works on Windows machines. Thirdly, allocating is slow and it'd be better to use borrowed C strings for `Archive`.

Ideally provide both high-level interface (for compatibility between Linux/Windows as in stdlib - think of &OsStr) and low-level interface for performance (useful for password crackers :)).

**Comment by muja** [comment] 2018-07-05 21:38
Hi, this is a reasonable issue. The problem is that I'm not using pure Rust, but an underlying C/C++ wrapper is invoked and `String`s are converted to `c_str`s back and forth etc. I'm just wondering whether your proposal is still possible

**Comment by muja** [comment] 2023-06-23 00:15
You can now use more types for archive filenames, similar to std::fs methods. For passwords unfortunately I'm not sure how to go forward that would suit your needs.
I'm closing for now, but feel free to reopen or comment in #32 if you can elaborate on your use case a bit more.

**Closed by muja** 2023-06-23 00:15 UTC
